spring:
  application:
    name: microservice-consumer-movie-feign
server:
  port: 8020
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    prefer-ip-address: true