spring:
  application:
    name: microservice-consumer-movie
server:
  port: 7901
user: 
  userServicePath: http://localhost:7900/user/getList
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    prefer-ip-address: true